// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'NA',
    appId: 'NA',
    messagingSenderId: '303977032353',
    projectId: 'kabootar-4b5d6',
    authDomain: 'NA',
    storageBucket: 'NA',
    measurementId: 'G-6PCJ6K6V2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'NA',
    appId: '1:303977032353:android:eef6465891dee138049ee0',
    messagingSenderId: 'NA',
    projectId: 'kabootar-4b5d6',
    storageBucket: 'NA',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'NA',
    appId: '1:303977032353:ios:c7c4fa1ee58d6796049ee0',
    messagingSenderId: '303977032353',
    projectId: 'kabootar-4b5d6',
    storageBucket: 'kabootar-4b5d6.firebasestorage.app',
    iosBundleId: 'com.example.kabootar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'NA',
    appId: '1:303977032353:ios:c7c4fa1ee58d6796049ee0',
    messagingSenderId: 'NA',
    projectId: 'kabootar-4b5d6',
    storageBucket: 'kabootar-4b5d6.firebasestorage.app',
    iosBundleId: 'com.example.kabootar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'NAc',
    appId: '1:303977032353:web:62564845e101c907049ee0',
    messagingSenderId: 'NA',
    projectId: 'kabootar-4b5d6',
    authDomain: 'kabootar-4b5d6.firebaseapp.com',
    storageBucket: 'kabootar-4b5d6.firebasestorage.app',
    measurementId: 'G-4RE18378WF',
  );
}
